name: Setup CMake
description: Fetches and installs the requested or latest CMake version
branding:
  icon: package
  color: orange
inputs:
  cmake-version:
    description: The version to request
    default: '' # will select "latest" release unless version is specified

runs:
  using: composite
  steps:
    - name: Authenticate GitHub CLI
      shell: pwsh
      run: Write-Output ${{github.token}} | gh auth login --with-token
    - name: Get CMake Release Information
      id: information
      shell: pwsh
      run: |
        $Arch = switch ("${{runner.arch}}") {
          { $IsMacOS } { "universal" }
          "X64" { "x86_64" }
          "ARM64" { if ($IsWindows) { $PSItem.ToLower() } else { "aarch64" } }
          default {
            Write-Output "::error title=Unsupported Platform::Unknown or Unsupported architecture"
            exit 1
          }
        }
        echo "$Arch"
        $Release = gh release view "${{inputs.cmake-version}}" --repo kitware/cmake --json tagName,assets
        $Asset = [PSCustomObject](${Release}
                | jq --arg os "${{runner.os}}" --arg arch "${Arch}" --from-file ${{github.action_path}}/assets.jq
                | ConvertFrom-Json)
        if ("${{runner.os}}" -eq "macOS") {
          echo $Asset
          Get-ChildItem Env:
        }
        $Arguments = @{ Path = "${env:GITHUB_OUTPUT}"; Encoding = "UTF8" }
        Add-Content @Arguments -Value "archive=$($Asset.name)"
        Add-Content @Arguments -Value "url=$($Asset.url)"
        Add-Content @Arguments -Value "key=$($Asset.id)"
        Add-Content @Arguments -Value "path=cmake-${{inputs.cmake-version}}-${Arch}"
    - name: Restore Cache
      id: restore
      uses: actions/cache/restore@v6
      with:
        path: ${{runner.temp}}/${{steps.information.outputs.archive}}
        key: ${{steps.information.outputs.key}}
    - name: Download Archive
      if: steps.restore.outputs.cache-hit != 'true'
      shell: pwsh
      run: >-
        curl --silent --fail --show-error
        --location
        --remote-name
        --output-dir ${{runner.temp}}
        "${{steps.information.outputs.url}}"
    - name: Save Archive
      if: steps.restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@v6
      with:
        path: ${{runner.temp}}/${{steps.information.outputs.archive}}
        key: ${{steps.information.outputs.key}}
    - name: Prepare Tool Directory
      shell: pwsh
      run: New-Item -Path "${{runner.temp}}/${{steps.information.outputs.path}}" -ItemType Directory
    - name: Extract CMake
      shell: pwsh
      run: >-
        tar
        --extract
        --gunzip
        --strip-components=$(if ($IsMacOS) { 3 } else { 1 })
        --directory "${{runner.temp}}/${{steps.information.outputs.path}}"
        --file "${{runner.temp}}/${{steps.information.outputs.archive}}"
    - name: Set System PATH
      shell: pwsh
      run: >-
        Add-Content
        -Encoding UTF8
        -Path "${env:GITHUB_PATH}"
        -Value "${{runner.temp}}/${{steps.information.outputs.path}}/bin"
    - name: Show CMake Version
      shell: pwsh
      run: cmake --version
